name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache dotnet tools
        id: cache-dotnet-tools
        uses: actions/cache@v3
        with:
          path: $HOME/.dotnet/tools
          key: ${{ runner.os }}-dotnet-tools
      
      - name: Install dotnet tools
        if: steps.cache-dotnet-tools.outputs.cache-hit != 'true'
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          NUGET_XMLDOC_MODE: skip
        shell: pwsh
        run: |
          dotnet tool update --global dotnet-sonarscanner
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
      
#      - name: Cache NuGet-Packages
#        id: cache-nuget-packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.nuget/packages
#          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

#      - name: Restore Packages
#        if: steps.cache-nuget-packages.outputs.cache-hit != 'true'
#        env:
#          DOTNET_CLI_TELEMETRY_OPTOUT: 1
#          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
#          NUGET_XMLDOC_MODE: skip
#        run: dotnet restore
        
      - name: Build
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          NUGET_XMLDOC_MODE: skip
        run: dotnet build -c release --nologo -p:ContinuousIntegrationBuild=true
      
      - name: Test and analyze
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          NUGET_XMLDOC_MODE: skip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          $file = "Extensions.Dictionary\bin\Release\netstandard2.0\Extensions.Dictionary.dll"
          $version = (Get-Command ([System.IO.Path]::Combine($pwd.Path, $file))).Version.ToString(3)
          
          .\.tools\dotnet-sonarscanner begin /k:"SiberaIndustries_Extensions.Dictionary" /o:"siberaindustries" /d:sonar.host.url="https://sonarcloud.io" /v:"$version" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet test -c release --no-restore --nologo /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          .\.tools\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Create NuGet package
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          NUGET_XMLDOC_MODE: skip
        run: dotnet pack -o . -c release --no-restore --no-build --nologo

      - name: Upload NuGet-Package
        uses: actions/upload-artifact@v2
        with:
          name: NuGet-Packages
          path: ./*.nupkg
